import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  gewu: [
    {
      type: "category",
      label: "Physics",
      link: {
        type: "generated-index",
        title:"物理",
      },
      collapsed: false,
      items: ["gewu/lllx","gewu/wldx","gewu/semi_phy","gewu/quan_phy"],
    },
    {
      type: "category",
      label: "EE",
      link: {
        type: "generated-index",
        title:"硬件学习相关",
      },
      collapsed: false,
      items: ["gewu/szdzjs","gewu/re_szdzjs","gewu/dlll","gewu/dgx"],
    },
    {
      type: "category",
      label: "CS",
      link: {
        type: "generated-index",
        title:"软件学习相关",
      },
      collapsed: false,
      items: ["gewu/discretemath","gewu/ds","gewu/python","gewu/typescript"],
    },
    {
      type: "category",
      label: "Drive",
      link: {
        type: "generated-index",
        title:"驾驶技术",
      },
      collapsed: false,
      items: ["gewu/jsjs"],
    },
  ],
  zhizhi: [
    {
      type: "category",
      label: "Literature",
      link: {
        type: "generated-index",
        title:"文学",
      },
      collapsed: false,
      items: ["zhizhi/zgddwxzc","zhizhi/xsmmg","zhizhi/wxllrm"],
    },
    {
      type: "category",
      label: "Economy",
      link: {
        type: "generated-index",
        title:"经济",
      },
      collapsed: false,
      items: ["zhizhi/zssn","zhizhi/zjwg"],
    },
    {
      type: "category",
      label: "PaperReading",
      link: {
        type: "generated-index",
        title:"论文阅读",
      },
      collapsed: false,
      items: ["zhizhi/hrls","zhizhi/3b&ztx"],
    },
  ],
};

export default sidebars;
